### ISSUE TITLE
no message

### ISSUE THREAD

**Issue by glary** [zk520it/ZKZoomLayout#1]
QQ XXXXXX

**Comment by kavin-zhou** [comment]
企业扣扣可以直接搜到我啊

**Comment by glary** [comment]
@dev-zhoukang   我没企业qq的。 我们是趣赚科技

**Comment by glary** [comment]
@dev-zhoukang  你用过RSKImageCropper那个库吗

**Comment by kavin-zhou** [comment]
用过 裁剪图片用的

**Comment by glary** [comment]
@dev-zhoukang  我想让他双击（默认）是最小比例。然后旋转的时候充满整个框。这个该怎么实现呢？ 加qq详聊下吧。 我的扣扣81990319
